<?php

return [
    'Zend\Mail',
    'Zend\Mvc\Plugin\Identity',
    'Zend\Mvc\Plugin\Prg',
    'Zend\Log',
    'Zend\Serializer',
    'Zend\Cache',
    'Zend\I18n',
    'Zend\Mvc\Plugin\FlashMessenger',
    'Zend\Form',
    'Zend\InputFilter',
    'Zend\Filter',
    'Zend\Hydrator',
    'Zend\Navigation',
    'Zend\Router',
    'Zend\Session',
    'Zend\Validator',
    'DoctrineModule',
    'DoctrineORMModule',
    'AssetManager',
    'TwbBundle',
    'Uthando',
];
