<?php declare(strict_types=1);
/**
 * Uthando CMS (http://www.shaunfreeman.co.uk/)
 *
 * @package   Blog\Form
 * @author    Shaun Freeman <shaun@shaunfreeman.co.uk>
 * @copyright Copyright (c) 2018 Shaun Freeman. (http://www.shaunfreeman.co.uk)
 * @license   see LICENSE
 */

namespace Blog\Form;


use Blog\Entity\PostEntity;
use Core\Form\FormBase;
use Zend\Form\FormInterface;

/**
 * Class PostForm
 *
 * @package Blog\Form
 * @method PostEntity getData($flag = FormInterface::VALUES_NORMALIZED)
 */
final class PostForm extends FormBase
{
    /**
     * @return bool
     */
    public function isValid(): bool
    {
        $this->checkSeo();
        return parent::isValid(); // TODO: Change the autogenerated stub
    }

    /**
     * Check to see if seo is empty, if it is use title for value.
     */
    public function checkSeo(): void
    {
        $seo = $this->get('seo');
        $title = $this->get('title');

        if ($seo->getValue() == '') {
            $value = $title->getValue();
            $seo->setValue($value);
        }
    }
}