<?php $this->headTitle('Edit User') ?>


<div class="breadcrumb">
    <!-- Breadcrumbs -->
    <?= $this->navigation(Uthando\Admin\Service\Factory\NavigationFactory::class)
        ->breadcrumbs()
        ->setSeparator(' / '); ?>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <i class=" fa fa-pencil"></i> <?=$this->translate('Edit User');?>
            <?= $this->escapeHtml($this->user->email) ?>
        </div>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
        <span class="col-sm-offset-2">
            <button type="submit" form="edit-user-form" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
            <i class="fa fa-save"></i>
            </button>
            <a href="<?=$this->url('admin/user-admin');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
                <i class="fa fa-reply"></i>
            </a>
        </span>
    </div>
</div>
