# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  PHP: true
exclude_paths:
  - bin/*
  - build/*
  - config/*
  - data/*
  - public/*
  - test/*
  - unittest/*
  - themes/*
  - vendor/*
  - view/*
