<?php $this->bootstrap()->enable(); ?>
<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('rating', 'general'); ?>

    <?=$this->headLink()
        ->appendStylesheet($this->basePath('css/uthando-admin.css')); ?>

    <style>
        html {padding-top: 60px;}
    </style>
</head>
<body>
<div id="container">
    <header id="header" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a type="button" id="button-menu" class="pull-left"><i class="fa fa-indent fa-lg"></i></a>
                <a class="navbar-brand" href="<?= $this->url('home'); ?>">Uthando CMS</a>
            </div>
        </div>
    </header>

    <div class="container">

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <?=$this->tbFlashMessenger()->render(); ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <?=$this->content; ?>
            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col-md-12">
                <footer id="footer">
                    <p>
                        &copy; 2013 - <?=date('Y'); ?> by <a href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights reserved.
                    </p>
                </footer>
            </div>
        </div>
    </div>

</div>

<?=$this->inlineScript()
    ->appendFile($this->basePath('js/uthando-admin.js')); ?>

<script>
    admin.basePath = '<?=$this->basePath();?>';
</script>

<?=$this->placeholder('js-scripts');?>

</body>
</html>
