<?php $this->bootstrap()->enable(); ?>
<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('rating', 'general'); ?>

    <?=$this->headLink()
        ->appendStylesheet($this->basePath('css/uthando-admin.css')); ?>
</head>
<body>
<div id="container">
    <header id="header" class="navbar navbar-default navbar-static-top">
        <div class="navbar-header">
            <a type="button" id="button-menu" class="pull-left"><i class="fa fa-indent fa-lg"></i></a>
            <a class="navbar-brand" href="<?= $this->url('home'); ?>">Uthando CMS</a>
        </div>
        <ul class="nav pull-right">
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user"></i> <?= $this->identity()->getFullName(); ?>
                    <i class="fa fa-caret-down"></i>
                </a>
                <?= $this->uthandoNavigation(\UthandoAdmin\Service\AdminUserNavigationFactory::class)
                    ->uthandoTbMenu()
                    ->setUlClass('dropdown-menu dropdown-menu-right'); ?>
            </li>
        </ul>
    </header>

    <nav id="column-left">
        <?= $this->navigation(\UthandoAdmin\Service\AdminNavigationFactory::class)
            ->menu()
            ->setPartial('uthando-admin/partial/side-bar'); ?>
    </nav>

    <div id="content">
        <div class="page-header">
            <div class="container-fluid">
                <div class="pull-right">
                    <?=$this->placeholder('header-buttons');?>
                </div>
                <h1><?=$this->pageTitle;?></h1>
                <nav class="breadcrumb">
                    <?=$this->navigation(\UthandoAdmin\Service\AdminNavigationFactory::class)
                        ->breadcrumbs()
                        ->setRenderInvisible(true)
                        ->setSeparator(' / ');
                    ?>
                </nav>
            </div>
        </div>

        <div id="alerts" class="container-fluid">
            <?=$this->tbFlashMessenger()->render(); ?>
        </div>

        <div class="container-fluid">
            <?=$this->content; ?>
        </div>
        <hr>
    </div>

    <footer id="footer">
        <p>
            &copy; 2013 - <?=date('Y'); ?> by <a href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights reserved.
        </p>
    </footer>
</div>

<?=$this->inlineScript()
    ->appendFile($this->basePath('js/uthando-admin.js')); ?>

<script>
    admin.basePath = '<?=$this->basePath();?>';
</script>

<?=$this->placeholder('js-scripts');?>

</body>
</html>
