<?php
/** @var \UthandoThemeManager\Model\WidgetModel $widget */
$widget = $this->widget;
$numPerRow = $this->params['numPerRow'] ?? 2;
$posts = $this->postHelper()->getRecent(12);
$c=0;
?>


<?php if ($widget->isShowTitle()):?>
    <h2 class="col-md-12"><?=$this->escapeHtml($widget->getTitle());?></h2>
<?php endif; ?>

<?php foreach($posts as $post): ?>
    <?php $c++;?>
<div class="col-md-<?=(12 / $numPerRow);?>">
    <div class="thumbnail">
        <a href="<?=$this->url('blog', [
            'post-item' => $this->escapeHtml($post->getSlug()),
        ]);?>">
            <img class="image-reponsive" src="<?=$this->basePath($this->escapeHtml($post->getImage()));?>" alt="<?=$this->escapeHtml($post->getTitle());?>">
        </a>
        <div class="caption">
            <h3><a href="<?=$this->url('blog', [
                    'post-item' => $this->escapeHtml($post->getSlug()),
                ]);?>"><?=$this->escapeHtml($post->getTitle());?></a></h3>
            <p><?=$this->postHelper()->getLead($post, 20);?></p>
            <p>
                <a href="<?=$this->url('blog', [
                    'post-item' => $this->escapeHtml($post->getSlug()),
                ]);?>" class="btn btn-default" role="button">View Post</a>
            </p>
        </div>
    </div>
</div>
    <?php if (($c % $numPerRow) === 0):?>
        <div class="clearfix"></div>
    <?php endif; ?>
<?php endforeach;?>

<hr>
