
<form action="<?=$this->url($this->escapeHtml($this->params['action'] ?? ''));?>" method="post">
    <div class="input-group">
        <input type="search" placeholder="Start Searching..." id="search" name="search" class="form-control">
        <div class="input-group-btn">
            <button type="submit" class="btn btn-default">
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
</form>

<hr>
