<?php $this->bootstrap()->enable();?>
<?=$this->doctype(); ?>
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <?=$this->headTitle('Uthando CMS')->setSeparator(' - ')->setAutoEscape(false);?>
    
        <?=$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>
    
        <!-- styles -->
        <?=$this->headLink()
            ->appendStylesheet($this->basePath('/themes/default/assets/css/styles.css'));?>
        
        <!-- Scripts -->
        <?=$this->headScript()
            ->appendFile($this->basePath('/js/site.js'))
            ->appendFile($this->basePath('/js/html5.js'), 'text/javascript', ['conditional' => 'lt IE 9']);?>

  </head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$this->url('home'); ?>"><img src="<?=$this->basePath('/img/zf2-logo.png');?>"><span>Uthando CMS</span></a>
            </div>
            
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?=$this->uthandoNavigation('UthandoAdmin\Navigation')->uthandoDbMenu('Main')->setUlClass('nav navbar-nav');?>
                
                <?php if ($this->identity()):?>
				<div class="dropdown">
					<ul class="nav navbar-nav navbar-right">
						<li>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#"> 
                                <i class="glyphicon glyphicon-user"></i> <?=$this->identity()->getFullName();?> 
    					        <b class="caret"></b>
                            </a>
                        <?=$this->uthandoNavigation('UthandoUser\Navigation')->uthandoTbMenu()->setUlClass('dropdown-menu');?>
						</li>
					</ul>
				</div>
			<?php endif; ?>
			</div><!--/.nav-collapse -->
		</div>
	</nav>

	<div class="container">
        <div class="row">
            <?=$this->tbFlashMessenger()->render(); ?>
        </div>
	   
        <div class="row">
            <?=$this->content; ?>
            <hr>
        </div>
        
        <div class="row">
            <footer>
        		<p>&copy; 2013 - <?=date('Y'); ?> by <a
        				href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
        			reserved.
        		</p>
        	</footer>
    	</div>
	</div>
	<!-- /container -->
    <div class="loading site-loading">
		<!-- Place at bottom of page -->
	</div>
</body>
</html>
