<?=$this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?=$this->headTitle('Uthando CMS')->setSeparator(' - ')->setAutoEscape(false);?>

    <?=$this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

    <!-- styles -->
    <?=$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/styles.css')
    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.css');?>
    
    <!-- Scripts -->
    <?=$this->headScript()
    ->appendFile('//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js')
    ->appendFile($this->basePath() . '/js/bootstrap.js')
    ->appendFile($this->basePath() . '/js/site.js')
    ->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', ['conditional' => 'lt IE 9']);?>

  </head>

<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="<?=$this->url('home'); ?>">Uthando CMS</a>
				<div class="nav-collapse">
                    <?=$this->uthandoNavigation()->uthandoDbMenu('Main')->setUlClass('nav'); ?>
                </div><!--/.nav-collapse -->
                <?php if ($this->identity()):?>
                <div class="dropdown">
					<ul class="nav pull-right">
						<li><a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i
								class="icon-user"></i> <?=$this->identity()->getFullName();?> 
    					        <b class="caret"></b>
						</a>
                        <?=$this->uthandoNavigation('UthandoUser\Navigation')->uthandoTbMenu()->setUlClass('dropdown-menu');?> 
						</li>
					</ul>
				</div>
				<?php endif; ?>
			</div>
		</div>
	</div>

	<div class="container">
        <div class="row">
            <?=$this->tbFlashMessenger()->render(); ?>
        </div>
	   
        <div class="row">
            <?=$this->content; ?>
            <hr>
        </div>
        
        <div class="row">
            <footer>
        		<p>&copy; 2013 - <?=date('Y'); ?> by <a
        				href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
        			reserved.
        		</p>
        	</footer>
    	</div>
	</div>
	<!-- /container -->
    <div class="loading site-loading">
		<!-- Place at bottom of page -->
	</div>
</body>
</html>
