<?php $this->headTitle('Sessions') ?>
<?=$this->ztbFlashMessenger()->render();?>

<?php if (count($this->models) > 0):?>

<table class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="id">User Id</th>
			<th data-field="name">Name</th>
			<th data-field="modified">Modified</th>
			<th data-field="lifetime">Expires</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
	   <?php /* @var $row \Application\Model\Session */ ?>
		<?php foreach($this->models as $row):?>
		
		<tr>
			<td><?=$this->escapeHtml($row->getId());?></td>
			<td><?=$this->escapeHtml($row->getName());?></td>
			<td><?=$this->escapeHtml($this->formatDate('@'.$row->getModified()));?></td>
			<td><?=$this->escapeHtml($this->formatDate('@'.($row->getModified() + $row->getLifetime())));?></td>
			<td>
				<a data-toggle="modal" class="btn" href="<?=$this->url('admin/session/view', array(
					'id' => $row->getId()
				));?>" data-target="#viewSession<?=$row->getId();?>">View Data</a>
				<!-- Modal -->
				<div id="viewSession<?=$row->getId(); ?>" class="modal hide fade" tabindex="-1">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" >&times;</button>
						<h3 id="myModalLabel">Session Data</h3>
					</div>
					<div class="modal-body">
						<p>Loading…</p>
					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal">Close</button>
					</div>
				</div>
				&nbsp;
				<!-- Button to trigger modal -->
                <a href="#sessionModel<?=$row->getId();?>" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="sessionModel<?=$row->getId();?>" tabindex="-1">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="sessionModel<?=$row->getId();?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/session/delete');?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this user.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="id" value="<?=$row->getId();?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>


<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/session/page')
);?>

<?php else:?>
<h4>No sessions where returned by search.</h4>
<?php endif;?>


