<?php $this->headTitle('Change Password') ?>

<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Change Password');?></h3>
            </div>
            <div class="panel-body">
                <?=$this->form($this->form);?>
                <button type="submit" form="change-password-form" data-toggle="tooltip" title="<?=$this->translate('Reset Password');?>" class="btn btn-primary">
                    <?=$this->translate('Change Password');?>
                </button>
            </div>
        </div>
    </div>
</div>
