<?php $this->headTitle('Login') ?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Please Sign In');?></h3>
            </div>
            <div class="panel-body">
                <?php if ($this->isLoginError): ?>
                    <div class="alert alert-warning" role="alert">
                        Incorrect login and/or password.<br>
                        <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                    </div>
                <?php endif; ?>
                <?=$this->form($this->form);?>
                <button type="submit" form="login-form" data-toggle="tooltip" title="<?=$this->translate('Sign In');?>" class="btn btn-lg btn-primary btn-block">
                    <?=$this->translate('Sign In');?>
                </button>
            </div>
        </div>
    </div>
</div>
