<?php $this->headTitle('Forgot Password') ?>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Reset Password');?></h3>
            </div>
            <div class="panel-body">
                <p>Enter your e-mail address below to reset your password</p>
                <?=$this->form($this->form);?>
                <button type="submit" form="password-reset-form" data-toggle="tooltip" title="<?=$this->translate('Reset Password');?>" class="btn btn-primary">
                    <?=$this->translate('Reset Password');?>
                </button>
            </div>
        </div>
    </div>
</div>