<?php $this->bootstrap()->enable();?>
<?=$this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?=$this->headTitle($this->escapeHtml($this->themeOptions('site_name')))
        ->setSeparator(' - ')
        ->setAutoEscape(false);?>

    <?=$this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>
    
    <!-- styles -->
    <?=$this->headLink([
        'rel'  => 'shortcut icon',
        'href' => $this->basePath('/img/favicon.ico')
    ])->appendStylesheet($this->basePath('css/uthando.css'))
        ->appendStylesheet($this->themePath('assets/css/styles.css'));?>
  </head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$this->url('home'); ?>">
                    <?=$this->escapeHtml($this->themeOptions('site_name'));?>
                </a>
            </div>
            
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?=$this->uthandoNavigation()->uthandoTbDbMenu('main')->setUlClass('nav navbar-nav');?>
                
                <?php if ($this->identity()):?>
				<div class="dropdown">
					<ul class="nav navbar-nav navbar-right">
						<li>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#"> 
                                <i class="fa fa-user fa-lg"></i> <?=$this->identity()->getFullName();?>
    					        <b class="caret"></b>
                            </a>
                        <?=$this->uthandoNavigation('UthandoUser\Navigation')->uthandoTbMenu()->setUlClass('dropdown-menu');?>
						</li>
					</ul>
				</div>
			    <?php endif; ?>
			</div><!--/.nav-collapse -->
		</div>
	</nav>

	<div class="container-fluid">
        <?=$this->widget('group-layout-top');?>

        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <?=$this->tbFlashMessenger()->render(); ?>
                    </div>
                </div>

                <?=$this->widget('group-content');?>

            </div>
        </div>

        <?=$this->widget('group-layout-bottom');?>

        <hr>

        <div class="row">
            <div class="col-md-12">
                <footer>
                    <p>&copy; 2013 - <?=date('Y'); ?> by <a
                            href="http://www.shaunfreeman.name">
                            <?=$this->escapeHtml($this->themeOptions('site_name'));?>
                        </a>. All rights
                        reserved. <span><?=$this->socialLinks()->render();?></span>
                    </p>
                </footer>
            </div>
    	</div>
	</div>
    <?=$this->inlineScript()
        ->appendFile($this->basePath('/js/uthando.js'));?>

    <?=$this->placeholder('js-scripts');?>
</body>
</html>
