<?=$this->doctype(); ?>
<?=$this->bootstrap()->enable();?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?=$this->headTitle('Uthando CMS')->setSeparator(' - ')->setAutoEscape(false);?>

    <?=$this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

    <!-- styles -->
    <?=$this->headLink()
        ->appendStylesheet($this->basePath('css/uthando-admin.css'))
        ->appendStylesheet($this->basePath('css/uthando.css'));?>
    
    <!-- Scripts -->
    <?=$this->headScript()
        ->appendFile($this->basePath('/js/bootstrap.js'));?>
  </head>

<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?=$this->url('home'); ?>">
                    Uthando CMS
                </a>
            </div>
            <?php if ($this->identity()):?>
            <ul class="nav pull-right">
                <li><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user"></i> <?= $this->identity()->getFullName(); ?>
                        <i class="fa fa-caret-down"></i>
                    </a>

                    <?= $this->uthandoNavigation('UthandoUser\Navigation')
                        ->uthandoTbMenu()
                        ->setUlClass('dropdown-menu dropdown-menu-right'); ?>
                </li>
            </ul>
            <?php endif;?>
        </div>
    </nav>

    <nav id="column-left">
        <?=$this->navigation('navigation')->menu()->setPartial('uthando-admin/partial/side-bar');?>
        <?= $this->navigation('UthandoAdmin\Navigation')
            ->menu()
            ->setPartial('uthando-admin/partial/side-bar'); ?>
    </nav>

	<div class="container">
        <div class="page-header">
            <div class="container-fluid">
                <div class="pull-right">
                    <?=$this->placeholder('header-buttons');?>
                </div>
                <h1><?=$this->pageTitle;?></h1>
                <nav class="breadcrumb">
                    <?=$this->navigation('UthandoAdmin\Navigation')
                        ->breadcrumbs()
                        ->setRenderInvisible(true)
                        ->setSeparator(' / ');
                    ?>
                </nav>
            </div>
        </div>

        <div id="alerts" class="container-fluid">
            <?=$this->tbFlashMessenger()->render(); ?>
        </div>

        <div class="container-fluid">
            <?=$this->content; ?>
        </div>
        <hr>

		<footer>
			<p>&copy; 2013 - <?=date('Y'); ?> by <a
					href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
				reserved.
			</p>
		</footer>

	</div>
	<!-- /container -->
    <?= $this->inlineScript()
        ->appendFile($this->basePath('js/uthando.js'))
        ->appendFile($this->basePath('js/uthando-admin.js')); ?>

    <script>
        admin.basePath = '<?=$this->basePath();?>';
    </script>
</body>
</html>
