<div class="tab-wrap row-fluid">

	<ul id="dashboardTabs" class="nav nav-tabs">
	    <li><a href="#dashboard" data-toggle="tab">Dashboard</a></li>
	    <li><a href="#phpinfo" data-toggle="tab">PHP Info</a></li>
	</ul>
	
	<div id="tab-content" class="tab-content">
		<div class="tab-pane" id="dashboard">
			<h2>Not yet implemented</h2>
		</div>
	    <div class="tab-pane" id="phpinfo">
			<table class="span6 offset3">
				<thead>
					<tr>
						<th colspan="2">&nbsp;</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th colspan="2">&nbsp;</th>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>
							<?php
							ob_start();
							phpinfo();
							$phpinfo = ob_get_contents();
							ob_end_clean();
		
							preg_match_all('#<body[^>]*>(.*)</body>#siU', $phpinfo, $output);
							$output = preg_replace('#<table#', '<table class="table table-bordered"', $output[1][0]);
							$output = preg_replace('#(\w),(\w)#', '\1, \2', $output);
							$output = preg_replace('#border="0" cellpadding="3" width="600"#', '', $output);
							$output = preg_replace('#<hr />#', '', $output);
							$output = str_replace('<div class="center">', '', $output);
							$output = str_replace('</div>', '', $output);
		
							echo $output;
							?>
						</td>
					</tr>
				</tbody>
			</table>
	 	</div>
	</div>
</div>

<script>
$(function () {
	$('#dashboardTabs a:first').tab('show');
});
</script>
