
<ol class="breadcrumb">
    <!-- Breadcrumbs -->
    <?= $this->navigation(Uthando\Admin\Service\Factory\NavigationFactory::class)
        ->breadcrumbs()
        ->setSeparator(' / '); ?>
</ol>

<h1>Manage Posts</h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('admin/post-admin', ['action'=>'add']); ?>">
        New Post
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Post Title</th>
        <th>Date Created</th>
        <th>Status</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($posts as $post): ?>
        <tr>
            <td><?= $this->escapeHtml($post->id); ?></td>
            <td>
                <a href="<?= $this->url('blog/post', ['action'=>'view', 'id'=>$post->id]); ?>">
                    <?= $this->escapeHtml($post->title); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($post->dateCreated->format('d/m/Y')); ?></td>
            <td><?= $this->escapeHtml($post->status()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('admin/post-admin', [
                    'action' => 'edit',
                    'id' => $this->escapeHtml($post->id),
                ]); ?>" title="<?=$this->translate('Edit');?>">
                    <span class="fa fa-pencil" ></span> Edit
                </a>
                <!-- Button to trigger modal -->
                <a href="#confirm-delete-<?=$this->escapeHtml($post->id);?>" class="btn btn-danger" title="<?=$this->translate('Delete');?>" data-toggle="modal" data-target="#confirm-delete-<?=$this->escapeHtml($post->id);?>">
                    <i class="fa fa-trash"></i>
                    Delete
                </a>
                <!-- Modal -->
                <div class="modal fade" id="confirm-delete-<?=$this->escapeHtml($post->id);?>">

                    <div class="modal-dialog">
                        <div class="modal-content">

                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h3 id="confirm-<?=$this->escapeHtml($post->id);?>Label"><?=$this->translate('Warning');?></h3>
                            </div>

                            <form class="form-horizontal"  method="post" action="<?= $this->url('admin/post-admin', [
                                    'action'=>'delete',
                                    'id'=>$this->escapeHtml($post->id),
                            ]); ?>">
                                <div class="modal-body">
                                    <p><?=$this->translate('Are you sure you want to delete:');?> <?=$this->escapeHtml($post->title); ?>.</p>
                                    <h4 class="text-danger"><?=$this->translate('This action cannot be undone');?></h4>
                                </div>
                                <input type="hidden" name="id" value="<?=$this->escapeHtml($post->id);?>">
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">
                                        <?=$this->translate("No Don't Do It");?>
                                    </button>
                                    <button type="submit" name="submit" class="btn btn-danger" value="delete">
                                        <?=$this->translate('Yes Delete It');?>
                                    </button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

<?= $this->paginationControl($posts,
    'Sliding',
    'partial/paginator',
    ['route' => 'admin/post-admin']); ?>
