<?php $this->bootstrap()->enable();?>
<?=$this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?=$this->headTitle('Uthando CMS')->setSeparator(' - ')->setAutoEscape(false);?>

    <?=$this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>
    
    <!-- styles -->
    <?=$this->headLink([
        'rel'  => 'shortcut icon',
        'href' => $this->basePath('/img/favicon.ico')
    ])->appendStylesheet($this->basePath('/default/assets/css/styles.css'));?>

    <!-- Scripts -->
    <?=$this->headScript()
        ->appendFile($this->basePath('/js/site.js'));?>
  </head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$this->url('home'); ?>">
                    Uthando CMS
                </a>
            </div>
            
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?=$this->uthandoNavigation()->uthandoTbDbMenu('main')->setUlClass('nav navbar-nav');?>
                
                <?php if ($this->identity()):?>
				<div class="dropdown">
					<ul class="nav navbar-nav navbar-right">
						<li>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#"> 
                                <i class="fa fa-user fa-lg"></i> <?=$this->identity()->getFullName();?>
    					        <b class="caret"></b>
                            </a>
                        <?=$this->uthandoNavigation('UthandoUser\Navigation')->uthandoTbMenu()->setUlClass('dropdown-menu');?>
						</li>
					</ul>
				</div>
			<?php endif; ?>
			</div><!--/.nav-collapse -->
		</div>
	</nav>

	<div class="container">
        <div class="row">
            <div class="col-md-12">
                <?=$this->tbFlashMessenger()->render(); ?>
            </div>
        </div>
	   
        <div class="row">
            <div class="col-md-12">
                <?=$this->content; ?>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-md-12">
                <footer>
                    <p>&copy; 2013 - <?=date('Y'); ?> by <a
                            href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
                        reserved.
                    </p>
                </footer>
            </div>
    	</div>
	</div>
    <?=$this->inlineScript();?>
</body>
</html>
