
<div class="col-sm-8">
    <h1>Welcome to Uthando CMS</h1>
    <?php foreach($this->posts as $post): ?>

    <h3>
        <a href="<?=$this->url('post', [
            'action' => 'view',
            'id'     => $post->id->toString()
        ]);?>">
            <?= $this->escapeHtml($post->title); ?>
        </a>
    </h3>

    <p>
        Published: <?= $this->escapeHtml($post->dateCreated->format('jS \of F Y g:i a')); ?>
        | Tags:  <?= $this->tagHelper()->renderTags($post->getTags()); ?>
    </p>

    <p>
        <?= $this->escapeHtml($post->content); ?>
    </p>

    <hr>

    <?php endforeach; ?>
    <?= $this->paginationControl($posts,
        'Sliding',
        'blog/partial/paginator',
        ['route' => $this->route, 'routeParams' => $this->routeParams]); ?>

</div>

<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Popular Tags</h3>
        </div>
        <div class="panel-body">
            <?= $this->tagHelper($this->route)->renderTagCloud($tagCloud, $this->route); ?>
        </div>
    </div>
</div>


