<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Uthando CMS')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$this->url('home'); ?>">
                    Uthando CMS
                </a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?=$this->navigation('navigation')->twbmenu()->setUlClass('nav navbar-nav');?>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <!-- Flash messenger -->
        <div class="row">
            <div class="col-md-12">
                <?=$this->flashMessenger()->render(); ?>
            </div>
        </div>
        <!-- /Flash messenger -->

        <!-- Main Content -->
        <div class="row">
            <div class="col-md-12">
                <?=$this->content; ?>
            </div>
        </div>
        <!-- /Main Content -->

        <hr>

        <!-- Footer -->
        <div class="row">
            <div class="col-md-12">
                <footer>
                    <p>&copy; 2017 - <?=date('Y'); ?> by <a
                                href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
                        reserved.
                    </p>
                </footer>
            </div>
        </div>
        <!-- /Footer -->
    </div>
        <!-- /container -->
        <?= $this->inlineScript() ?>
    </body>
</html>
