<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
        <?=$this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false);?>

        <?=$this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('rating', 'general');?> 
        
        <!-- Styles -->
        <?=$this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'img/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'])
        ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
        ->appendStylesheet($this->basePath() . '/themes/admin/assets/css/styles.css');?>

        <!-- Scripts -->
        <?=$this->headScript()
        ->appendFile('//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js')
        ->appendFile($this->basePath() . '/themes/admin/assets/js/jquery.datatable.js')
        ->appendFile($this->basePath() . '/js/bootstrap.js')
        ->appendFile($this->basePath() . '/themes/admin/assets/js/admin.js');?>
       
    </head>
<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="<?=$this->url('home'); ?>">Uthando CMS</a>
				<div class="nav-collapse">
                    <?=$this->uthandoNavigation('UthandoAdmin\Navigation')->uthandoTbMenu();?>
                </div><!--/.nav-collapse -->
                <?php if ($this->identity()):?>
				<div class="dropdown">
					<ul class="nav pull-right">
						<li><a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i
								class="icon-user"></i> <?=$this->identity()->getFullName();?> 
    					        <b class="caret"></b>
						</a>
                        <?=$this->uthandoNavigation('UthandoUser\Navigation')->uthandoTbMenu()->setUlClass('dropdown-menu');?>
						</li>
					</ul>
				</div>
				<?php endif; ?>
			</div>
		</div>
	</div>

	<div class="container">
        <div class="row">
            <?=$this->partial('uthando-common/partial/tb-flashmessage'); ?>
        </div>
	   
        <div class="row">
            <?=$this->content; ?>
            <hr>
        </div>
        
        <div class="row">
            <footer>
        		<p>&copy; 2013 - <?=date('Y'); ?> by <a
        				href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
        			reserved.
        		</p>
        	</footer>
    	</div>
	</div>
	<!-- /container -->

	<div class="loading admin-loading">
		<!-- Place at bottom of page -->
	</div>
        <?=$this->inlineScript();?>
    </body>
</html>

