<?php $this->bootstrap()->enable();?>
<?=$this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <?=$this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false);?>

        <?=$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('rating', 'general');?> 
        
        <!-- Styles -->
        <?=$this->headLink()
            ->appendStylesheet($this->basePath('/themes/admin/assets/css/styles.css'));?>

        <!-- Scripts -->
        <?=$this->headScript()
            ->appendFile($this->basePath('/themes/admin/assets/js/loading-overlay.min.js'))
            ->appendFile($this->basePath('/themes/admin/assets/js/jquery.datatable.js'))
            ->appendFile($this->basePath('/themes/admin/assets/js/admin.js'))
            ->appendFile($this->basePath('/themes/admin/assets/js/jquery.ajaxWidgetPanel.js'))
            ->appendFile($this->basePath('/themes/admin/assets/js/bootbox.min.js'));?>
       
    </head>
    <body>
        
    	<nav class="navbar navbar-default navbar-fixed-top">
    		<div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home'); ?>">
                        <img src="<?=$this->basePath('/img/zf2-logo.png');?>">
                        <span>Uthando CMS</span>
                    </a>
                </div>
                
    			<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
                    <?=$this->uthandoNavigation('UthandoAdmin\Navigation')
                        ->uthandoTbMenu()
                        ->setUlClass('nav navbar-nav')
                        ->setMaxDepth(1);?>
                    
                    <?php if ($this->identity()):?>
    				<div class="dropdown">
    					<ul class="nav navbar-nav navbar-right">
    						<li><a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i
    								class="glyphicon glyphicon-user"></i> <?=$this->identity()->getFullName();?> 
        					        <b class="caret"></b>
    						</a>
                            <?=$this->uthandoNavigation('UthandoUser\Navigation')->uthandoTbMenu()->setUlClass('dropdown-menu');?>
    						</li>
    					</ul>
    				</div>
    			<?php endif; ?>
    			</div><!--/.nav-collapse -->
    		</div>
    	</nav>
    
    	<div class="container">
            <div id="alerts" class="row">
                <?=$this->tbFlashMessenger()->render(); ?>
            </div>
            
            <div class="row">
                <?=$this->content; ?>
                <hr>
            </div>
            
            <div class="row">
                <footer>
            		<p>&copy; 2013 - <?=date('Y'); ?> by <a
            				href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
            			reserved.
            		</p>
            	</footer>
        	</div>
    	</div>
    	<!-- /container -->
        <?=$this->inlineScript();?>
    </body>
</html>

